### ISSUE TITLE
GeekZone Studio

### ISSUE THREAD

**Issue by SamuelLeyva** [GameDev-Cuba/creadores-cubanos-videojuegos-website#40]
Logo del Estudio:
![geekzone__studios_icono](https://user-images.githubusercontent.com/51203506/182699090-a479a287-f514-42f2-af0c-79abd5671256.jpg)

**¨Making Dreams¨**
GeekZone Studio es un estudio creativo conformado por una sola persona hasta el momento, apasionada por la creación, tanto de videojuegos como la animación 2D,el objetivo del estudio es hacer llegar todas estas creaciones al mercado nacional e internacional reflejando siempre un toque de cubanía...
Redes Sociales:
Instagram: [https://www.instagram.com/geekzonestudio_01/](url)
Facebook: @geekzoneCuba

**Productos:**
-------------------------------------------------------
**Vivir del Cuento El juego:**
Acompaña a Pánfilo en sus aventuras y desventuras por alcanzar pesca'o! Una carrera contra el tiempo! Lucha contra los coleros e impide que roben tu turno en la cola del pesca'o!
Cansado de hacer colas todo el día??? adquiere nuestro juego y relájate mientras acabas con todos esos coleros que te robaron el turno en la cola del pollo!(este juego no promueve la violencia, cualquier similitud con la vida real es pura coincidencia)

Fotos de Vivir del Cuento El Juego:
![promo panfi 1](https://user-images.githubusercontent.com/51203506/182702211-bedf94af-dcd6-4c82-a714-f7c32d5c38a5.jpg)
![promo panfi 3](https://user-images.githubusercontent.com/51203506/182702310-cb30bd21-9a55-4c08-8160-e04ea12e97d2.jpg)
![promo panfi 4](https://user-images.githubusercontent.com/51203506/182702334-51f40a68-00fa-49fe-96e2-a5560142444b.jpg)
![promo panfi 5](https://user-images.githubusercontent.com/51203506/182702380-78d4f7d7-4e3a-4d2e-8553-dbfe91fb5106.jpg)
![promo panfi 6](https://user-images.githubusercontent.com/51203506/182702409-ba8c52a2-2a83-4ee9-97cb-71ee2db4c16c.jpg)
![promo panfi 7](https://user-images.githubusercontent.com/51203506/182702446-a814dc05-88db-4a22-a171-7b25cf814435.jpg)
![promo_panfi_2](https://user-images.githubusercontent.com/51203506/182702486-da26eb57-6773-4296-819e-41f9ef4332c1.jpg)
Enlace de descarga: [https://www.apklis.cu/application/com.GeekZone.panfilo](url)
------------------------------------------------------------------------------------------------------------------
**Capitol Defense:**
Proteje el Capitolio de La Habana! Imnumerables hordas de monstruos se aproximan a nuestra tierra en busca del poder que oculta el Diamante del Capitolio,embarcate en una aventura que decidirá el destino de la nación y la humanidad! Descubre el secreto que guarda el brillante mientras luchas contra monstruos de todo tipo ayudado por los valientes guerreros de La Logia del Diamante!

Fotos de Capitol Defense:
![promo defensetower1](https://user-images.githubusercontent.com/51203506/182704544-63bba4fd-084c-4562-895b-ae42b78cfac5.jpg)

![promo defensetower2](https://user-images.githubusercontent.com/51203506/182704669-8135a846-0fa9-453a-a184-4c6f9516405b.jpg)
![promo defensetower3](https://user-images.githubusercontent.com/51203506/182704717-373004af-6747-4562-bb59-6c0da15da444.jpg)

Enlace de descarga: [https://www.apklis.cu/application/com.GeekZoneStudio.CapitolDefense](url)
----------------------------------------------------------------------------------------------------------------------------
**Armandito Run:**
Carnota ha perdido sus pullovers y han terminado regados por las azoteas de La Habana! Ayuda a Armandito a recuperar la mayor cantidad de pullovers posibles! Compite contra jugadores de todo el país! escala en el Ranking Nacional hasta convertirte en el mejor jugador de todo el país!

Fotos de Armandito Run:
![armandito promo 1](https://user-images.githubusercontent.com/51203506/182705280-c7563bd5-6dcc-4be7-9ffd-4d21ea7bd047.jpg)
![armandito promo 2](https://user-images.githubusercontent.com/51203506/182705304-afc1689d-4017-4dd0-9153-fc1f9226eb94.jpg)
![armandito promo 3](https://user-images.githubusercontent.com/51203506/182705329-80d8272f-cab7-4ca7-ae9d-145cd4b39dd3.jpg)
![armandito promo 4](https://user-images.githubusercontent.com/51203506/182705340-0c041568-34fd-494f-b812-d145f91a0aa0.jpg)
![fondo armandito run](https://user-images.githubusercontent.com/51203506/182705352-233771ef-c806-4e6b-a892-c9df2eb9f9f3.jpg)

Enlace de descarga: [https://www.apklis.cu/application/com.GeekZoneStudio.ArmanditoRun](url)
---------------------------------------------------------------------------------------------------------------------------
**Match Mandaos:**
Es hora de ir en busca de los mandaos!

Un videojuego al más puro estilo de candy crush saga pero llevado a la cotidianidad del día a día del cubano! Combina los productos y hazlos explotar para ganar!

-100 niveles llenos de acción!

-4 diferentes escenarios habaneros!

-Potenciadores especiales!

Mecánicas adictivas!

Un nuevo juego de puzzles match nunca antes visto ya está aquí que te tendrá incontables horas poniendo a prueba tu habilidad!

Fotos de Matcha mandaos:
![PromoMatchmandaos1](https://user-images.githubusercontent.com/51203506/182705827-0c6e8e33-b8a9-41ed-8db9-7ca80cf400e5.jpg)
![PromoMatchmandaos2](https://user-images.githubusercontent.com/51203506/182705858-1bcecef0-5880-4481-a367-5eedfb638956.jpg)
![PromoMatchmandaos3](https://user-images.githubusercontent.com/51203506/182705894-e2233b82-46a2-4a48-8a34-cdac5191ee8b.jpg)
![PromoMatchmandaos4](https://user-images.githubusercontent.com/51203506/182705908-b3d609e2-677d-4ce4-a509-1a49ef859dc4.jpg)

Enlace de descarga: [https://www.apklis.cu/application/com.GeekZoneStudio.MatchMandaos](url)

---------------------------------------------------------------------------------------------------------------------------
**The Fisherman:**
La temporada de pesca a llegado al malecón de La Habana! Atrapa tantos peces como puedas!Compite contra otros pescadores de todo el país hasta ser el mejor!
Fotos de The Fisherman:
![rgdrg](https://user-images.githubusercontent.com/51203506/182707406-d101551b-7604-49fa-a88c-f15e56c591aa.jpg)
Enlace de Descarga: [https://www.apklis.cu/application/com.GeekZoneStudio.TheFisherMan](url)
----------------------------------------------------------------------------------------------------------------------------------
**Bubble Shooter Habana Pop:**
Un nuevo juego de Bubble Shooter ya está aquí!

Bubble Shooter Habana Pop es un interesante y desafiante juego de disparo de burbujas. Mientras mantenemos las mecánicas del clásico juego le hemos agregado una pizca de cubanía para crear un videojuego de disparo de burbujas único! 

Combina 3 o más burbujas, dispara estratégicamente, rescata a los monstruos y supera los niveles llenos de burbujas coloridas! Descarga Bubble Shooter Habana Pop y alcanza la cima del cielo!

Fotos de bubble Shooter:
![promobubble1](https://user-images.githubusercontent.com/51203506/182708476-4b251e16-ca3c-4fdc-9e11-2b8a5acf0b9c.jpg)
![promobubble2](https://user-images.githubusercontent.com/51203506/182708510-6bfb63dd-1627-4a9f-9831-197e59f876f8.jpg)
![promobubble3](https://user-images.githubusercontent.com/51203506/182708521-18927fa5-76ae-4df1-9afe-f0596fcebef2.jpg)

Enlace de Descarga: [https://www.apklis.cu/application/com.youcompany.halloweencandy](url)
-------------------------------------------------------------------------------------------------------------------------------
**The Last Soldier(en desarrollo):**
the Last Soldier es un juego de survival shooter en 3ra persona en la cual nos encontraremos en la piel de un soldado de las tropas especiales de Cuba el cual es el ultimo soldado en pie que queda debido a la invasión enemiga, la misión del jugaodr es sobrevivir y eliminar a las constantes oleadas de enemigos, se prevee en el futuro un apartado de misiones, el juego se desarrolla en las inmediaciones del Capitolio de La Habana usando representaciones graficas en 3d de diferentes edifcios y calles de la vida real para poder sumergir mejor al jugador en la historia del juego,el juego se encuentra actualmente en desarollo.
Fotos de The Last Soldier:
![1111](https://user-images.githubusercontent.com/51203506/182710742-7388b16b-fa06-410a-ba17-ea4fe42f6b8a.JPG)
![2222](https://user-images.githubusercontent.com/51203506/182710768-2ba63b46-e8b8-40d2-b8eb-e96ec0ea14a3.JPG)
![3333](https://user-images.githubusercontent.com/51203506/182710776-877d171c-5784-421c-964a-1fc479f251ec.JPG)

---------------------------------------------------------------------------------------------------------------------------------
**Parque G: la Serie(en producción):**
Parque G es una serie animada que se encuentra actualmente en producción la cual seguirá las aventuras y desventuras de 4 amigos 
en la avenida más famosa de La Habana conocida porpularmente como ¨Parque G¨
Fotos de Parque G:
![Parque G poster 2](https://user-images.githubusercontent.com/51203506/182711223-68edb1fc-8fb7-4ed1-bcd0-62f9906378cd.jpg)
![pegatina Parque G](https://user-images.githubusercontent.com/51203506/182711328-60be57ed-3d74-4b94-a91d-66cdee94ea1b.jpg)
![poster protas](https://user-images.githubusercontent.com/51203506/182711348-21e4f83d-6cbb-49ab-ab22-eafc724a281f.jpg)

----------------------------------------------------------------------------------------------------------------------------------------
Equipo de GeekZone Studio:
Samuel Leyva
![Capture+_2022-08-03-16-47-16~2](https://user-images.githubusercontent.com/51203506/182711603-aa366894-0de6-4e31-af5d-172b97d6035c.png)

Fundador-programador-diseñador
Graduado de tecnico Medio en informática, fundador de GeekZoneStudio desde el año 2019, un estudio creativo que abarca desde los videojuegos hasta la animación 2d, con muchas ganas de crear y aprender un poco cada día más de estos fantasticos mundos audiovisuales.

**Comment by arianfornaris** [comment]
Hola. Parque G es un juego o una serie?

**Comment by arianfornaris** [comment]
Hecho!

https://www.videojuegoscuba.org/estudios/geek-zone/
