### ISSUE TITLE
Agrégame como productor musical y sound designer

### ISSUE THREAD

**Issue by VerianCS** [GameDev-Cuba/creadores-cubanos-videojuegos-website#57]
Hola, soy Brian .AV 
![Ilustración38 (3)-min](https://user-images.githubusercontent.com/56204242/210795874-8167a3f5-db5a-4a48-821e-298e985b7b4a.png)
(Cosmic Trigger)
Estudiante de lic. en ciencias informáticas y música, diseñador sonoro y productor musical desde hace 4 años. He hecho temas musicales para streamers, intros de canales y algunas novelas gráficas, también he participado en proyectos colaborativos de mediano tamaño en instituciones del Egrem. 

Contacto:
-Correo: zafkiel023@gmail.com
-Telegram: @BiellStarsea
-Páginas y plataformas sociales donde me puedes encontrar:  https://linktr.ee/ryasnvaeil

Ejemplos de mi trabajo:
https://soundcloud.com/cosmictrigger12

**Comment by arianfornaris** [comment]
Gracias!

Tienes algún logo que te represente?

También un texto hablando un poco más sobre tu trabajo seria bueno. Este es un ejemplo de perfil: https://www.videojuegoscuba.org/creadores/arian-fornaris/

**Comment by arianfornaris** [comment]
Ah, ya veo que me habias puesto una imágen. Esa misma funciona para el perfil. Solo seria bueno tener un texto un poco más desarrollado para la descripción de tu perfil.

**Comment by arianfornaris** [comment]
Por cierto, cuál es tu nombre completo?

**Comment by VerianCS** [comment]
Brian ALfaro Veranes

**Comment by arianfornaris** [comment]
Ok gracias!

**Comment by arianfornaris** [comment]
Listo.

Estás aquí: https://www.videojuegoscuba.org/creadores/brian-alfaro/

Siempre puedes editor tus datos aquí: https://github.com/GameDev-Cuba/creadores-cubanos-videojuegos-website/edit/main/content/es/creadores/brian-alfaro/page.md

Haces un pull request y actualizamos la página.
Por ejemplo, puedes poner que estás abierto a colaborar con proyectos dentro de cuba.
